CarpeDeumBundle\Entity\Calendar:
    type: entity
    table: CALENDAR
    uniqueConstraints:
        LANG_DATE:
            columns:
                - LANG
                - DATE
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        lang:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
                default: ''
            column: LANG
        date:
            type: date
            nullable: false
            options:
                default: '0000-00-00'
            column: DATE
        liturYear:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: A
            column: LITUR_YEAR
        liturDay:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: LITUR_DAY
        color:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: PURPLE
            column: COLOR
        colorInfo:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: COLOR_INFO
        celebration:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: CELEBRATION
        celebration2:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: CELEBRATION2
        happyNameDay:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: HAPPY_NAME_DAY
        thoughtId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: 'ANCIENNE VERSION'
            column: THOUGHT_ID
        saintTitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_TITLE
        saintSubtitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_SUBTITLE
        saintOptional:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: SAINT_OPTIONAL
        saintText:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_TEXT
        saintCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_CREDITS
        saintInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_INTERNAL_REF
        saintPic:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_PIC
        saintPicCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SAINT_PIC_CREDITS
        oration:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: ORATION
        orationSource:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: ORATION_SOURCE
        orationCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: ORATION_CREDITS
        orationInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: ORATION_INTERNAL_REF
        readingTitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING_TITLE
        readingSubtitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING_SUBTITLE
        reading:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING
        readingSource:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: UNUSED
            column: READING_SOURCE
        readingCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING_CREDITS
        readingInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING_INTERNAL_REF
        reading2Title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING2_TITLE
        reading2Subtitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING2_SUBTITLE
        reading2:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING2
        reading2Source:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: UNUSED
            column: READING2_SOURCE
        reading2Credits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING2_CREDITS
        reading2InternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: READING2_INTERNAL_REF
        psalmTitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PSALM_TITLE
        psalmSubtitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PSALM_SUBTITLE
        psalm:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PSALM
        psalmSource:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: UNUSED
            column: PSALM_SOURCE
        psalmCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PSALM_CREDITS
        psalmInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PSALM_INTERNAL_REF
        gospel:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL
        gospelSource:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_SOURCE
        gospelCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_CREDITS
        gospelInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_INTERNAL_REF
        gospelPic:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_PIC
        gospelPicCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_PIC_CREDITS
        gospelAudio:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_AUDIO
        gospelAudioCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPEL_AUDIO_CREDITS
        gospelcommentary:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPELCOMMENTARY
        gospelcommentarySource:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPELCOMMENTARY_SOURCE
        gospelcommentaryCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPELCOMMENTARY_CREDITS
        gospelcommentaryInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPELCOMMENTARY_INTERNAL_REF
        gospelcommentaryAudio:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPELCOMMENTARY_AUDIO
        gospelcommentaryAudioCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: GOSPELCOMMENTARY_AUDIO_CREDITS
        gospelcommentaryNumLikes:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: GOSPELCOMMENTARY_NUM_LIKES
        gospelcommentaryNumComments:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: GOSPELCOMMENTARY_NUM_COMMENTS
        thoughtTitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: THOUGHT_TITLE
        thought:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: THOUGHT
        thoughtCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: THOUGHT_CREDITS
        thoughtPic:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: THOUGHT_PIC
        thoughtPicCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: THOUGHT_PIC_CREDITS
        thoughtInternalRef:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: THOUGHT_INTERNAL_REF
        thoughtNumLikes:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: THOUGHT_NUM_LIKES
        thoughtNumComments:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: THOUGHT_NUM_COMMENTS
    lifecycleCallbacks: {  }
