CarpeDeumBundle\Entity\Comment:
    type: entity
    table: COMMENTS
    indexes:
        ITEM_TYPE:
            columns:
                - ITEM_TYPE_old
                - ITEM_ID
                - DATE
        IN_REPLY_TO:
            columns:
                - IN_REPLY_TO
                - DATE
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        itemType:
            type: string
            nullable: false
            length: 50
            options:
                fixed: true
                default: ''
            column: ITEM_TYPE
        itemTypeOld:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: PROFILE
            column: ITEM_TYPE_old
        itemId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: ITEM_ID
        inReplyTo:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: IN_REPLY_TO
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: ACCOUNT_ID
        accountName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: ACCOUNT_NAME
        accountPic:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: ACCOUNT_PIC
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: TEXT
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
        ip:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: IP
        moderator:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: MODERATOR
        hidden:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: HIDDEN
        adminHidden:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: ADMIN_HIDDEN
        adminSilenced:
            type: boolean
            nullable: false
            column: ADMIN_SILENCED
        numComments:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_COMMENTS
        numLikes:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_LIKES
    lifecycleCallbacks: {  }
