CarpeDeumBundle\Entity\Places:
    type: entity
    table: PLACES
    indexes:
        GEO_LAT:
            columns:
                - GEO_LAT
                - GEO_LNG
        IMPORT_SOURCE:
            columns:
                - IMPORT_SOURCE
                - IMPORT_ID
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: NAME
        type:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: CHURCH
            column: TYPE
        ancienType:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: ancien_type
        pic:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                default: ''
            column: PIC
        picCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PIC_CREDITS
        pics:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PICS
        picsList:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PICS_LIST
        vids:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: VIDS
        vidsList:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: VIDS_LIST
        geoLat:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
            column: GEO_LAT
        geoLng:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
            column: GEO_LNG
        infoAddress:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_ADDRESS
        infoAddress1:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_ADDRESS_1
        infoAddress2:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_ADDRESS_2
        infoAddressZip:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_ADDRESS_ZIP
        infoAddressCity:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_ADDRESS_CITY
        infoAddressCountry:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_ADDRESS_COUNTRY
        infoUrl:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_URL
        infoTel:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_TEL
        infoHistory:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: INFO_HISTORY
        scheduleNotes:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SCHEDULE_NOTES
        scheduleEucharist:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SCHEDULE_EUCHARIST
        ancienId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: ancien_id
        modified:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: MODIFIED
        importSource:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: IMPORT_SOURCE
        importId:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: IMPORT_ID
        importModified:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: IMPORT_MODIFIED
        numComments:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_COMMENTS
        numLikes:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_LIKES
        numCheckins:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_CHECKINS
    lifecycleCallbacks: {  }
