CarpeDeumBundle\Entity\ProfileVisit:
    type: entity
    table: PROFILEVISITS
    id:
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: ACCOUNT_ID
        visitorId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: VISITOR_ID
        dateIndex:
            type: date
            nullable: false
            options:
                default: '0000-00-00'
            id: true
            column: DATE_INDEX
    fields:
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
        counted:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: COUNTED
    lifecycleCallbacks: {  }
