CarpeDeumBundle\Entity\Search:
    type: entity
    table: SEARCHES
    indexes:
        ACCOUNT_ID:
            columns:
                - ACCOUNT_ID
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            column: ACCOUNT_ID
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: TITLE
        search:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SEARCH
    lifecycleCallbacks: {  }
