CarpeDeumBundle\Entity\TempConfirmMail:
    type: entity
    table: TEMP_CONFIRMEMAIL
    id:
        id:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: EMAIL
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            column: ACCOUNT_ID
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
    lifecycleCallbacks: {  }
