CarpeDeumBundle\Entity\Thought:
    type: entity
    table: THOUGHTS
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: 'ANCIENNE VERSION'
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        lang:
            type: string
            nullable: false
            length: 5
            options:
                fixed: true
                comment: 'ANCIENNE VERSION'
                default: ''
            column: LANG
        code:
            type: string
            nullable: false
            length: 15
            options:
                fixed: true
                comment: 'ANCIENNE VERSION'
                default: ''
            column: CODE
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 'ANCIENNE VERSION'
            column: TITLE
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 'ANCIENNE VERSION'
            column: TEXT
        credits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 'ANCIENNE VERSION'
            column: CREDITS
        image:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'ANCIENNE VERSION'
                default: ''
            column: IMAGE
        numComments:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: 'ANCIENNE VERSION'
                default: '0'
            column: NUM_COMMENTS
        numLikes:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: 'ANCIENNE VERSION'
                default: '0'
            column: NUM_LIKES
    lifecycleCallbacks: {  }
