CarpeDeumBundle\Entity\Update:
    type: entity
    table: UPDATES
    indexes:
        ACCOUNT_ID:
            columns:
                - ACCOUNT_ID
                - DATE
                - UPDATE_ID
    id: {  }
    fields:
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: ACCOUNT_ID
        accountName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: ACCOUNT_NAME
        accountPic:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: ACCOUNT_PIC
        updateId:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: UPDATE_ID
        updateDay:
            type: date
            nullable: false
            options:
                default: '0000-00-00'
            column: UPDATE_DAY
        updateHour:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: UPDATE_HOUR
        updateDetails:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: UPDATE_DETAILS
        private:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: PRIVATE
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
        numComments:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_COMMENTS
        numLikes:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_LIKES
    lifecycleCallbacks: {  }
