CarpeDeumBundle\Entity\CalendarText:
    type: entity
    table: CALENDARTEXT
    uniqueConstraints:
        LANG:
            columns:
                - LANG
                - TYPE
                - INTERNAL_REF
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        lang:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
                default: ''
            column: LANG
        type:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: ''
            column: TYPE
        internalRef:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: INTERNAL_REF
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: TITLE
        subtitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SUBTITLE
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: TEXT
        credits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: CREDITS
        image:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: IMAGE
        imageCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: IMAGE_CREDITS
        audio:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: AUDIO
        audioCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: AUDIO_CREDITS
    lifecycleCallbacks: {  }
