CarpeDeumBundle\Entity\CarpeBlog:
    type: entity
    table: CARPEBLOG
    indexes:
        FOLDER_ID:
            columns:
                - DRAFT
                - DATE
        HOME:
            columns:
                - LANG
                - DRAFT
                - DATE
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        lang:
            type: string
            nullable: false
            length: 5
            options:
                fixed: true
            column: LANG
        draft:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: DRAFT
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
        pretitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: PRETITLE
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: TITLE
        subtitle:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: SUBTITLE
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: TEXT
        html:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: HTML
        image:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: IMAGE
        imageCredits:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: IMAGE_CREDITS
        images:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: IMAGES
        video:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: VIDEO
        byline:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: BYLINE
        numComments:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_COMMENTS
        numLikes:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: NUM_LIKES
    lifecycleCallbacks: {  }
