CarpeDeumBundle\Entity\ClassifiedCandle:
    type: entity
    table: CLASSIFIEDCANDLES
    indexes:
        CLASSIFIED_ID:
            columns:
                - CLASSIFIED_ID
    id: {  }
    fields:
        classifiedId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: CLASSIFIED_ID
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: ACCOUNT_ID
        date:
            type: datetime
            nullable: false
            column: DATE
    lifecycleCallbacks: {  }
