CarpeDeumBundle\Entity\ContactTag:
    type: entity
    table: CONTACTTAGS
    id:
        fromAccountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: FROM_ACCOUNT_ID
        toAccountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: TO_ACCOUNT_ID
        tag:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            id: true
            column: TAG
    lifecycleCallbacks: {  }
