CarpeDeumBundle\Entity\Contact:
    type: entity
    table: CONTACTS
    indexes:
        ACCOUNT_ID2:
            columns:
                - ACCOUNT_ID2
                - ACCOUNT_ID1
    id:
        accountId1:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: ACCOUNT_ID1
        accountId2:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: ACCOUNT_ID2
    fields:
        bookmark1:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: BOOKMARK1
        bookmark2:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: BOOKMARK2
        friend1:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: FRIEND1
        friend2:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: FRIEND2
        block1:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: BLOCK1
        block2:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: BLOCK2
        notes1:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: NOTES1
        notes2:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: NOTES2
    lifecycleCallbacks: {  }
