CarpeDeumBundle\Entity\Like:
    type: entity
    table: LIKES
    id:
        itemType:
            type: string
            nullable: false
            length: 50
            options:
                fixed: true
                default: ''
            id: true
            column: ITEM_TYPE
        itemId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: ITEM_ID
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: ACCOUNT_ID
    fields:
        accountName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: ACCOUNT_NAME
        accountPic:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: ACCOUNT_PIC
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
    lifecycleCallbacks: {  }
