CarpeDeumBundle\Entity\NewsFolder:
    type: entity
    table: NEWSFOLDERS
    indexes:
        LANG:
            columns:
                - LANG
                - ONHOME
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        lang:
            type: string
            nullable: false
            length: 5
            options:
                fixed: true
            column: LANG
        onhome:
            type: boolean
            nullable: false
            column: ONHOME
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: TITLE
        image:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: IMAGE
    lifecycleCallbacks: {  }
