CarpeDeumBundle\Entity\Notice:
    type: entity
    table: NOTICES
    id:
        fromAccountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: FROM_ACCOUNT_ID
        toAccountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: TO_ACCOUNT_ID
        noticeId:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            id: true
            column: NOTICE_ID
    fields:
        noticeDetails:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: NOTICE_DETAILS
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
    lifecycleCallbacks: {  }
