CarpeDeumBundle\Entity\PlaceEdit:
    type: entity
    table: PLACEEDITS
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        accountId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: ACCOUNT_ID
        placeId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: PLACE_ID
        changes:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: CHANGES
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
        seen:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: SEEN
    lifecycleCallbacks: {  }
