CarpeDeumBundle\Entity\TempSignup:
    type: entity
    table: TEMP_SIGNUPS
    id:
        id:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: EMAIL
        lang:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                default: ''
            column: LANG
        client:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: WEB
            column: CLIENT
        dateBirth:
            type: date
            nullable: false
            options:
                default: '0000-00-00'
            column: DATE_BIRTH
        date:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: DATE
    lifecycleCallbacks: {  }
